title: Testing page
author: Hoang Le
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testing GitHub page
  
# social links
twitter_username: hoang_le_96
github_username:  hoangle96

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
